version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - backend
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    networks:
      - backend
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  cravefeed_backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - backend
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:admin@postgres:5432/postgres
      REDIS_URL: redis://redis:6379

networks:
  backend:
    driver: bridge